@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов для Менеджера файлов

Container(file_manager, "Менеджер файлов", "Go", "Реализует логику управления файлами.")

System_Boundary(c1, "Внутренние компоненты Менеджера файлов") {
    Component(delivery, "Delivery", "gRPC", "Обрабатывает входящие gRPC запросы.")
    Component(usecases, "Usecases", "Go", "Содержит основную бизнес-логику.")
    Component(repository, "Repository", "Go", "Обрабатывает доступ к данным и их хранение.")
}

Rel(delivery, usecases, "Использует")
Rel(usecases, repository, "Использует")

@enduml
