\c voblako_db;

CREATE TABLE IF NOT EXISTS public.user (
    id INT NOT NULL
        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL
        CHECK (email <> '')
        CONSTRAINT max_len_email CHECK(LENGTH(email) <= 100),
    password_hash TEXT NOT NULL
        CHECK (password_hash <> '')
        CONSTRAINT max_len_password_hash CHECK(LENGTH(password_hash) <= 256)
);
