//protoc --go_out=. --go-grpc_out=. --go-grpc_opt=paths=source_relative --go_opt=paths=source_relative *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: file.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerID       uint32                 `protobuf:"varint,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=Filename,proto3" json:"Filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetOwnerID() uint32 {
	if x != nil {
		return x.OwnerID
	}
	return 0
}

func (x *UploadFileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetFilesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerID       uint32                 `protobuf:"varint,1,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,3,opt,name=Offset,proto3" json:"Offset,omitempty"`
	WithDeleted   bool                   `protobuf:"varint,4,opt,name=WithDeleted,proto3" json:"WithDeleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesListRequest) Reset() {
	*x = GetFilesListRequest{}
	mi := &file_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesListRequest) ProtoMessage() {}

func (x *GetFilesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesListRequest.ProtoReflect.Descriptor instead.
func (*GetFilesListRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{1}
}

func (x *GetFilesListRequest) GetOwnerID() uint32 {
	if x != nil {
		return x.OwnerID
	}
	return 0
}

func (x *GetFilesListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFilesListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetFilesListRequest) GetWithDeleted() bool {
	if x != nil {
		return x.WithDeleted
	}
	return false
}

type GetFilesListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileMetadata        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilesListResponse) Reset() {
	*x = GetFilesListResponse{}
	mi := &file_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilesListResponse) ProtoMessage() {}

func (x *GetFilesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilesListResponse.ProtoReflect.Descriptor instead.
func (*GetFilesListResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{2}
}

func (x *GetFilesListResponse) GetFiles() []*FileMetadata {
	if x != nil {
		return x.Files
	}
	return nil
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	UserID        uint32                 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{3}
}

func (x *GetFileRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *GetFileRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileResponse) Reset() {
	*x = GetFileResponse{}
	mi := &file_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileResponse) ProtoMessage() {}

func (x *GetFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileResponse.ProtoReflect.Descriptor instead.
func (*GetFileResponse) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{4}
}

func (x *GetFileResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetFileResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetFileResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetFileMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	UserID        uint32                 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataRequest) Reset() {
	*x = GetFileMetadataRequest{}
	mi := &file_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataRequest) ProtoMessage() {}

func (x *GetFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{5}
}

func (x *GetFileMetadataRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *GetFileMetadataRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	OwnerID       uint32                 `protobuf:"varint,2,opt,name=OwnerID,proto3" json:"OwnerID,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=Filename,proto3" json:"Filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	StorageKey    string                 `protobuf:"bytes,6,opt,name=StorageKey,proto3" json:"StorageKey,omitempty"`
	UploadTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UploadTime,proto3" json:"UploadTime,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	DeletedTime   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=DeletedTime,proto3" json:"DeletedTime,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,10,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{6}
}

func (x *FileMetadata) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *FileMetadata) GetOwnerID() uint32 {
	if x != nil {
		return x.OwnerID
	}
	return 0
}

func (x *FileMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMetadata) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *FileMetadata) GetUploadTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadTime
	}
	return nil
}

func (x *FileMetadata) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *FileMetadata) GetDeletedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedTime
	}
	return nil
}

func (x *FileMetadata) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type UpdateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	UserID        uint32                 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	Size          int64                  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileRequest) Reset() {
	*x = UpdateFileRequest{}
	mi := &file_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileRequest) ProtoMessage() {}

func (x *UpdateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFileRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *UpdateFileRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateFileRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UpdateFilenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	UserID        uint32                 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=Filename,proto3" json:"Filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFilenameRequest) Reset() {
	*x = UpdateFilenameRequest{}
	mi := &file_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFilenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilenameRequest) ProtoMessage() {}

func (x *UpdateFilenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilenameRequest.ProtoReflect.Descriptor instead.
func (*UpdateFilenameRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateFilenameRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *UpdateFilenameRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UpdateFilenameRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	UserID        uint32                 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_file_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteFileRequest) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *DeleteFileRequest) GetUserID() uint32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

var File_file_proto protoreflect.FileDescriptor

const file_file_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"file.proto\x12\bprotobuf\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x11UploadFileRequest\x12\x18\n" +
	"\aOwnerID\x18\x01 \x01(\rR\aOwnerID\x12\x1a\n" +
	"\bFilename\x18\x02 \x01(\tR\bFilename\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12 \n" +
	"\vContentType\x18\x04 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\x03R\x04Size\"\x7f\n" +
	"\x13GetFilesListRequest\x12\x18\n" +
	"\aOwnerID\x18\x01 \x01(\rR\aOwnerID\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\rR\x05Limit\x12\x16\n" +
	"\x06Offset\x18\x03 \x01(\rR\x06Offset\x12 \n" +
	"\vWithDeleted\x18\x04 \x01(\bR\vWithDeleted\"D\n" +
	"\x14GetFilesListResponse\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.protobuf.FileMetadataR\x05files\"<\n" +
	"\x0eGetFileRequest\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\rR\x06UserID\"w\n" +
	"\x0fGetFileResponse\x12\x1a\n" +
	"\bFilename\x18\x01 \x01(\tR\bFilename\x12 \n" +
	"\vContentType\x18\x02 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12\x12\n" +
	"\x04Size\x18\x04 \x01(\x03R\x04Size\"D\n" +
	"\x16GetFileMetadataRequest\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\rR\x06UserID\"\x82\x03\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x18\n" +
	"\aOwnerID\x18\x02 \x01(\rR\aOwnerID\x12\x1a\n" +
	"\bFilename\x18\x03 \x01(\tR\bFilename\x12 \n" +
	"\vContentType\x18\x04 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\x03R\x04Size\x12\x1e\n" +
	"\n" +
	"StorageKey\x18\x06 \x01(\tR\n" +
	"StorageKey\x12:\n" +
	"\n" +
	"UploadTime\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"UploadTime\x12:\n" +
	"\n" +
	"UpdateTime\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"UpdateTime\x12<\n" +
	"\vDeletedTime\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vDeletedTime\x12\x1c\n" +
	"\tIsDeleted\x18\n" +
	" \x01(\bR\tIsDeleted\"g\n" +
	"\x11UpdateFileRequest\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\rR\x06UserID\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\x12\x12\n" +
	"\x04Size\x18\x04 \x01(\x03R\x04Size\"_\n" +
	"\x15UpdateFilenameRequest\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\rR\x06UserID\x12\x1a\n" +
	"\bFilename\x18\x03 \x01(\tR\bFilename\"?\n" +
	"\x11DeleteFileRequest\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\rR\x06UserID2\xf6\x03\n" +
	"\x04File\x12A\n" +
	"\n" +
	"UploadFile\x12\x1b.protobuf.UploadFileRequest\x1a\x16.protobuf.FileMetadata\x12M\n" +
	"\fGetFilesList\x12\x1d.protobuf.GetFilesListRequest\x1a\x1e.protobuf.GetFilesListResponse\x12>\n" +
	"\aGetFile\x12\x18.protobuf.GetFileRequest\x1a\x19.protobuf.GetFileResponse\x12K\n" +
	"\x0fGetFileMetadata\x12 .protobuf.GetFileMetadataRequest\x1a\x16.protobuf.FileMetadata\x12A\n" +
	"\n" +
	"UpdateFile\x12\x1b.protobuf.UpdateFileRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0eUpdateFilename\x12\x1f.protobuf.UpdateFilenameRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\n" +
	"DeleteFile\x12\x1b.protobuf.DeleteFileRequest\x1a\x16.google.protobuf.EmptyBOZMgithub.com/IlyaChgn/voblako/internal/pkg/file/delivery/grpc/protobuf;protobufb\x06proto3"

var (
	file_file_proto_rawDescOnce sync.Once
	file_file_proto_rawDescData []byte
)

func file_file_proto_rawDescGZIP() []byte {
	file_file_proto_rawDescOnce.Do(func() {
		file_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)))
	})
	return file_file_proto_rawDescData
}

var file_file_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_file_proto_goTypes = []any{
	(*UploadFileRequest)(nil),      // 0: protobuf.UploadFileRequest
	(*GetFilesListRequest)(nil),    // 1: protobuf.GetFilesListRequest
	(*GetFilesListResponse)(nil),   // 2: protobuf.GetFilesListResponse
	(*GetFileRequest)(nil),         // 3: protobuf.GetFileRequest
	(*GetFileResponse)(nil),        // 4: protobuf.GetFileResponse
	(*GetFileMetadataRequest)(nil), // 5: protobuf.GetFileMetadataRequest
	(*FileMetadata)(nil),           // 6: protobuf.FileMetadata
	(*UpdateFileRequest)(nil),      // 7: protobuf.UpdateFileRequest
	(*UpdateFilenameRequest)(nil),  // 8: protobuf.UpdateFilenameRequest
	(*DeleteFileRequest)(nil),      // 9: protobuf.DeleteFileRequest
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_file_proto_depIdxs = []int32{
	6,  // 0: protobuf.GetFilesListResponse.files:type_name -> protobuf.FileMetadata
	10, // 1: protobuf.FileMetadata.UploadTime:type_name -> google.protobuf.Timestamp
	10, // 2: protobuf.FileMetadata.UpdateTime:type_name -> google.protobuf.Timestamp
	10, // 3: protobuf.FileMetadata.DeletedTime:type_name -> google.protobuf.Timestamp
	0,  // 4: protobuf.File.UploadFile:input_type -> protobuf.UploadFileRequest
	1,  // 5: protobuf.File.GetFilesList:input_type -> protobuf.GetFilesListRequest
	3,  // 6: protobuf.File.GetFile:input_type -> protobuf.GetFileRequest
	5,  // 7: protobuf.File.GetFileMetadata:input_type -> protobuf.GetFileMetadataRequest
	7,  // 8: protobuf.File.UpdateFile:input_type -> protobuf.UpdateFileRequest
	8,  // 9: protobuf.File.UpdateFilename:input_type -> protobuf.UpdateFilenameRequest
	9,  // 10: protobuf.File.DeleteFile:input_type -> protobuf.DeleteFileRequest
	6,  // 11: protobuf.File.UploadFile:output_type -> protobuf.FileMetadata
	2,  // 12: protobuf.File.GetFilesList:output_type -> protobuf.GetFilesListResponse
	4,  // 13: protobuf.File.GetFile:output_type -> protobuf.GetFileResponse
	6,  // 14: protobuf.File.GetFileMetadata:output_type -> protobuf.FileMetadata
	11, // 15: protobuf.File.UpdateFile:output_type -> google.protobuf.Empty
	11, // 16: protobuf.File.UpdateFilename:output_type -> google.protobuf.Empty
	11, // 17: protobuf.File.DeleteFile:output_type -> google.protobuf.Empty
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_file_proto_init() }
func file_file_proto_init() {
	if File_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_proto_rawDesc), len(file_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_proto_goTypes,
		DependencyIndexes: file_file_proto_depIdxs,
		MessageInfos:      file_file_proto_msgTypes,
	}.Build()
	File_file_proto = out.File
	file_file_proto_goTypes = nil
	file_file_proto_depIdxs = nil
}
